Feature/task1
MariaSopkova/omp-bot pull request #1
Opened 2021-10-19 06:34 UTC by MariaSopkova

Реализация задачи 1

2021-10-19 16:24 UTC, LiFeAiR requested changes

2021-10-19 16:24 UTC, LiFeAiR commented on .idea/.gitignore
> +# Default ignored files
не надо папку **.idea** комитить в репозиторий
.idea/modules.xml

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/demo/subdomain/command_list.go
> +	outputMsgText += "\n"
тут что то с отступами
сделай в проекте
```go fmt ./...```

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/commander.go
> +type Commander interface {
этот интерфейс в итоге где то используется?

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/commander.go
> +	case "product":
это вынеси пожалуйста в константу

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/commander.go
> +	case "product":
это вынеси пожалуйста в константу

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/product/callback_list.go
> +			Subdomain:    "product",
**recommendation** и **product** вынеси пожалуйста в константу

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/product/callback_list.go
> +	if len(nextButton.Text) != 0 && len(prevButton.Text) != 0 {
за место if ... else if ... else if
лучше использовать `switch case`

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/product/command_default.go
> +		"command not found.\n" +
многострочные текстовые константы лучше окружать обратными слешами
пример
```
str := `я
очень 
длинная 
строка`
```

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/product/command_edit.go
> +	if len(args) < 2{
в общем у тебя тут беда с форматированием

2021-10-19 16:24 UTC, LiFeAiR commented on internal/app/commands/recommendation/product/command_get.go
> +	if err != nil{
и тут тоже)
`go fmt ./...`
обязательно!

2021-10-19 16:24 UTC, LiFeAiR commented on internal/service/recommendation/product/service.go
> +		return fmt.Errorf(msg)
если ты делаешь `return` то можно обойтись без `else`
да и код будет выглядеть легче

2021-10-19 16:24 UTC, LiFeAiR commented on internal/service/recommendation/product/service.go
> +		return false, fmt.Errorf("Product with id %d not found", id)
см предидущий комментарий

2021-10-19 17:18 UTC, MariaSopkova commented on .idea/.gitignore
> +# Default ignored files
удалила

2021-10-19 17:23 UTC, MariaSopkova commented on internal/app/commands/recommendation/product/command_default.go
> +		"command not found.\n" +
Сделано

2021-10-19 17:25 UTC, MariaSopkova commented on internal/app/commands/recommendation/product/command_edit.go
> +	if len(args) < 2{
поправлено

2021-10-19 17:25 UTC, MariaSopkova commented on internal/app/commands/recommendation/product/command_get.go
> +	if err != nil{
Done

2021-10-19 17:25 UTC, MariaSopkova commented on internal/app/commands/recommendation/product/command_default.go
> +		"command not found.\n" +
done

2021-10-19 17:46 UTC, MariaSopkova commented on internal/app/commands/demo/subdomain/command_list.go
> +	outputMsgText += "\n"
сделала

2021-10-19 17:46 UTC, MariaSopkova commented on internal/app/commands/recommendation/commander.go
> +type Commander interface {
удалила

2021-10-19 17:46 UTC, MariaSopkova commented on internal/app/commands/recommendation/commander.go
> +	case "product":
Вынесла. Не факт что это то, что ты имел в виду

2021-10-19 17:52 UTC, MariaSopkova commented on internal/service/recommendation/product/service.go
> +		return fmt.Errorf(msg)
done

2021-10-19 17:52 UTC, MariaSopkova commented on internal/service/recommendation/product/service.go
> +		return false, fmt.Errorf("Product with id %d not found", id)
done

2021-10-19 17:52 UTC, MariaSopkova commented on internal/app/commands/recommendation/product/command_get.go
> +	if err != nil{
done

2021-10-19 17:52 UTC, MariaSopkova commented on internal/app/commands/recommendation/product/command_edit.go
> +	if len(args) < 2{
done

2021-10-19 17:53 UTC, MariaSopkova commented on internal/app/commands/recommendation/commander.go
> +	case "product":
Вынесла. Не факт что это то, что ты имел в виду

2021-10-20 20:16 UTC, LiFeAiR approved these changes

2021-10-20 20:16 UTC, LiFeAiR commented on internal/app/commands/recommendation/product/callback_list.go
> +	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
на будущее принято сортировать импорты следующим образом
1 блок - стандартные библиотеки
2 блок - внутренние библиотеки проекта
3 блок - 3dparty библиотеки
пример:
```
"log"
"strconv"
"fmt"

tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"

"github.com/gogo/protobuf/types"
"github.com/pkg/errors"
```

2021-11-26 19:35 UTC, merged