Связь с api
MariaSopkova/omp-bot pull request #2
Opened 2021-11-28 14:17 UTC by MariaSopkova

2021-11-28 14:33 UTC, LiFeAiR requested changes

2021-11-28 14:33 UTC, LiFeAiR commented on internal/config/config.go
> +"path/filepath"
форматирование

2021-11-28 14:33 UTC, LiFeAiR commented on internal/service/recommendation/product/grpc_service.go
> +return nil, nil
форматирование

2021-11-28 14:33 UTC, LiFeAiR commented on internal/service/recommendation/product/grpc_service.go
> +func (s *GrpcProductService) Size() int {
этот метод нигде не используется

2021-11-28 14:33 UTC, LiFeAiR commented on internal/config/config.go
> +var cfg *Config
использование переменной внутри пакета для хранения конфига
это скорее антипаттерн
как и синглтоны

2021-11-28 16:29 UTC, MariaSopkova commented on internal/service/recommendation/product/grpc_service.go
> +func (s *GrpcProductService) Size() int {
Пока. Он будет использоваться дальше. В мультичтении.

2021-11-29 07:54 UTC, MariaSopkova commented on internal/service/recommendation/product/grpc_service.go
> +return nil, nil
Сделано

2021-11-29 08:15 UTC, LiFeAiR approved these changes

2021-11-29 08:20 UTC, merged